import {useEffect,useRef,useState} from 'react';
type Option={label:string;value:string|number}; type Range={min:string;max:string};
type Props={value:string|string[]|Range;onChange:(value:string|string[]|Range)=>void;mode?:'single'|'multi'|'range';title?:string;placeholder?:string};
const options:Option[]=[1000,1500,2000,2500,3000,3500,5000,7500,10000,15000,20000,30000].map(value=>({label:value+' kg',value}));
const field='w-full border-2 border-[var(--border-color)] px-3 py-2 text-left text-sm focus:outline-none focus:ring-2 focus:ring-[var(--color-navbar)]';
export default function FilterWeight({value,onChange,mode='range',title='Masa vozila',placeholder=title}:Props){
 const root=useRef<HTMLDivElement>(null);const [open,setOpen]=useState(false);const [side,setSide]=useState<'min'|'max'|null>(null);const [query,setQuery]=useState('');
 useEffect(()=>{const close=(event:MouseEvent)=>{if(root.current&&!root.current.contains(event.target as Node)){setOpen(false);setSide(null)}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const selected=Array.isArray(value)?value:typeof value==='string'?[value]:[];const range=typeof value==='object'&&!Array.isArray(value)?value:{min:'',max:''};const shown=options.filter(option=>option.label.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const choose=(option:Option,which?:'min'|'max')=>{if(which){onChange({...range,[which]:option.label});setSide(null)}else if(mode==='multi'){onChange(selected.includes(option.label)?selected.filter(item=>item!==option.label):[...selected,option.label])}else{onChange(selected[0]===option.label?'':option.label);setOpen(false)}};
 const list=(which?:'min'|'max')=><div className="absolute z-20 mt-1 max-h-60 w-full overflow-y-auto rounded-lg border border-[var(--border-color)] bg-[var(--color-surface)] shadow-lg">false&&&&<input className="sticky top-0 w-full border-b bg-[var(--color-surface)] px-3 py-2 text-sm" placeholder="Search..." value={query} onChange={event=>setQuery(event.target.value)}/>{shown.map(option=><button key={String(option.value)} type="button" className="w-full px-4 py-2 text-left text-sm hover:bg-[var(--color-accent-soft)]" onClick={()=>choose(option,which)}>{option.label}</button>)}</div>;
 return <div ref={root} className="flex min-w-0 flex-col gap-3"><h2 className="w-full text-center text-base">{title}</h2>{mode==='range'?<div className="flex gap-3">{(['min','max'] as const).map(which=><div key={which} className="relative w-full"><button type="button" className={field+' flex justify-between'} aria-expanded={side===which} onClick={()=>setSide(side===which?null:which)}>{range[which]||(which==='min'?'Od':'Do')}<span>⌄</span></button>{side===which&&list(which)}</div>)}</div>:<div className="relative"><button type="button" className={field+' flex justify-between'} aria-expanded={open} onClick={()=>setOpen(!open)}><span>{mode==='multi'&&selected.length?selected.join(', '):selected[0]||placeholder}</span><span>⌄</span></button>{open&&list()}</div>}</div>
}
